# Netlify deployment configuration
# https://docs.netlify.com/configure-builds/file-based-configuration/

[build]
  # Directory to publish (current directory since it's a static site)
  publish = "."
  
  # Build command (not needed for static HTML site)
  # command = ""

[build.environment]
  # Node.js version for any build processes
  NODE_VERSION = "18"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Performance headers
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirects for clean URLs (optional)
[[redirects]]
  from = "/projects/brand-identity"
  to = "/projects/brand-identity.html"
  status = 200

[[redirects]]
  from = "/projects/*"
  to = "/projects/:splat.html"
  status = 200

# Form handling - Enhanced email notifications
[template.environment]
  FORM_NOTIFICATION_EMAIL = "elefesramones51@gmail.com"
  
# Form notification settings for better email separation
[[plugins]]
  package = "netlify-plugin-form-submissions"

# Custom form success redirects
[[redirects]]
  from = "/contact"
  to = "/contact.html"
  status = 200

# 404 page redirect
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404
